package entity;
// Generated 2018-12-25 10:47:42 by Hibernate Tools 4.3.1



/**
 * Owners generated by hbm2java
 */
public class Owners  implements java.io.Serializable {


     private Integer idow;
     private int pesel;
     private String name;
     private String surname;
     private String address;

    public Owners() {
    }

    public Owners(int pesel, String name, String surname, String address) {
       this.pesel = pesel;
       this.name = name;
       this.surname = surname;
       this.address = address;
    }
   
    public Integer getIdow() {
        return this.idow;
    }
    
    public void setIdow(Integer idow) {
        this.idow = idow;
    }
    public int getPesel() {
        return this.pesel;
    }
    
    public void setPesel(int pesel) {
        this.pesel = pesel;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }




}


