package entity;
// Generated 2018-12-25 10:47:42 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Vehicles generated by hbm2java
 */
public class Vehicles  implements java.io.Serializable {


     private Integer idve;
     private String make;
     private String model;
     private Date year;
     private String color;
     private String plates;

    public Vehicles() {
    }

    public Vehicles(String make, String model, Date year, String color, String plates) {
       this.make = make;
       this.model = model;
       this.year = year;
       this.color = color;
       this.plates = plates;
    }
   
    public Integer getIdve() {
        return this.idve;
    }
    
    public void setIdve(Integer idve) {
        this.idve = idve;
    }
    public String getMake() {
        return this.make;
    }
    
    public void setMake(String make) {
        this.make = make;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public Date getYear() {
        return this.year;
    }
    
    public void setYear(Date year) {
        this.year = year;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getPlates() {
        return this.plates;
    }
    
    public void setPlates(String plates) {
        this.plates = plates;
    }




}


