package entity;
// Generated 2020-01-07 14:55:57 by Hibernate Tools 4.3.1



/**
 * Wiw generated by hbm2java
 */
public class Wiw  implements java.io.Serializable {


     private Integer idwiw;
     private int vid;
     private int oid;
     private int gid;

    public Wiw() {
    }

    public Wiw(int vid, int oid, int gid) {
       this.vid = vid;
       this.oid = oid;
       this.gid = gid;
    }
   
    public Integer getIdwiw() {
        return this.idwiw;
    }
    
    public void setIdwiw(Integer idwiw) {
        this.idwiw = idwiw;
    }
    public int getVid() {
        return this.vid;
    }
    
    public void setVid(int vid) {
        this.vid = vid;
    }
    public int getOid() {
        return this.oid;
    }
    
    public void setOid(int oid) {
        this.oid = oid;
    }
    public int getGid() {
        return this.gid;
    }
    
    public void setGid(int gid) {
        this.gid = gid;
    }




}


